enableGlobalCache: true

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.5.0.cjs

npmScopes:
  matrix-org:
    npmRegistryServer: "https://gitlab.matrix.org/api/v4/packages/npm/"
    npmAlwaysAuth: false
